name: Java

on: [push]

env:
  BUILD_TIMEOUT: 3

jobs:
  format-check:
    name: Check Code Formatting
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: {{ $BUILD_TIMEOUT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Check Format
        run: |
          mvn --batch-mode -Pverify-format clean compile
        shell: 'bash'

  codecov:
    name: Codecov
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.TIMEOUT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
#      - name: Install dependencies
#        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.TIMEOUT }}
    strategy:
      matrix:
        # run different builds with the listed java versions
        java: [ 8, 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install


  build-windows:
    runs-on: windows-latest
    timeout-minutes: ${{ env.TIMEOUT }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install


  build-macos:
    runs-on: macos-latest
    timeout-minutes: ${{ env.TIMEOUT }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install