name: Java

on: [push]

jobs:
  format-check:
    name: Check Code Formatting
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Check Format
        run: |
          mvn --batch-mode -Pverify-format clean compile
        shell: 'bash'

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # run different builds with the listed java versions
        java: [ 8, 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install
